version: '3'

services:
  web:
    build: ./app
    container_name: django-web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    restart: always
    env_file:
      - ./.env

  db:
    image: postgres
    container_name: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data/
    env_file:
      - ./.env.db

volumes:
  pgdata: