# Generated by Django 4.2.4 on 2023-11-06 17:18

from django.db import migrations
import markdownfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=markdownfield.models.MarkdownField(rendered_field='content_rendered'),
        ),
    ]
